added a handler.ts file for use in the login process, also improved t…
heyitsmass/BayView pull request #51
Opened 2023-10-24 15:50 UTC by Chappy122

added a handler.ts file for use in the login process, also improved the styles of the login page.

2023-10-24 23:51 UTC, rdoinhs approved these changes
LGTM. Time permitting, it would be ideal to revisit styles with a card-based layout or something similar to what we originally produced in the Figma sans ip for the user login flow (some type of unification).

2023-10-25 03:46 UTC, sonicspeed123 approved these changes
From what i see mostly style files were touched. Seems good to me since we can easily change these styles later on

2023-10-25 11:15 UTC, heyitsmass requested changes

2023-10-25 11:15 UTC, heyitsmass commented on public/images/adminBG.jpg
Keep in mind that background images limit web accessibility; Any components will be limited to colors contrasting this specific image and color which is not represented the same on every display.

Please reference the [w3c guidelines](https://www.w3.org/TR/css-backgrounds-3/#background-image)

- For accessibility reasons, authors should not use background images as the sole method of conveying important information. See [Web Content Accessibility Guideline F3](https://www.w3.org/TR/2008/NOTE-WCAG20-TECHS-20081211/F3) [[WCAG20]](https://www.w3.org/TR/css-backgrounds-3/#biblio-wcag20). Images are not accessible in non-graphical presentations, and background images specifically might be turned off in high-contrast display modes.

2023-10-27 01:45 UTC, merged