createItinerary() rough base implementation
heyitsmass/BayView pull request #57
Opened 2023-10-27 22:01 UTC by sonicspeed123

2023-10-27 22:09 UTC, heyitsmass requested changes
Please move this into the defaults of the Itinerary Model and use the documentation mongoose provides. 

```ts
export const itinerarySchema = new Schema<IItinerary>({
  startDate: { type: Date, required: true, default:Date.now },
  endDate: { type: Date, required: true, default: Date.now},
  events: [eventSchema]
});
```

Similarly, An Itinerary shouldn't have a default start time and end time if there's no event planned yet; That would imply there is some event coming up but one doesn't exist. Once an event is added into the itinerary, then the start time of the first event and the end time of the last event should be assigned to these values. 

https://mongoosejs.com/docs/middleware.html#pre

2023-10-27 22:15 UTC, heyitsmass commented on src/types/ItineraryManager.ts
> +    const newItinerary: Schema<IItinerary> = new Itineraries({
```ts
const newItinerary:HydratedDocument<IItinerary> = new Itineraries({startDate:Date.now(), endDate:Date.now()}); 
 ```

2023-10-28 23:36 UTC, heyitsmass approved these changes

2023-10-30 06:42 UTC, rdoinhs approved these changes
Good start. I appreciate the commented documentation.

2023-10-31 00:24 UTC, merged