Banner home input additions style changes
heyitsmass/BayView pull request #82
Opened 2023-11-17 14:14 UTC by rdoinhs

### Description
This PR modifies existing styles to input components among others and includes the following notable changes:

- Introduces banner component 
- Adds blur to itinerary title / adds it to home
- Refactors `[id]/page.tsx` to produce a dynamic way of rendering card components on home
  - Inline with this change, all card components should now be specified in the `initialCards` array at the top of the file
- Adds a select component as seen in the Figma mockups for Flights
- Refactors / modifies card and makes the title prop on card optional to allow for wider use outside of home / subnesting

### Motivation and Context
This furthers the vision to the Figma mockups and adds package changes / refines components for the introduction of future component functionality. The use of multiple flight card components in the video is for demonstration purposes and is not included the changes.

### Screenshots:

https://github.com/heyitsmass/BayView/assets/38991991/1f04babe-e7f3-49f3-8b4a-661ac91aef51

<img width="341" alt="Screenshot 2023-11-17 at 6 01 52 AM" src="https://github.com/heyitsmass/BayView/assets/38991991/c4044e57-3eeb-47b3-89a8-cc8b1b18f0ba">

### Additional Notes
N/A

### Types of changes
- [ ]  Bug fix (non-breaking change which fixes an issue)
- [x]  New feature (non-breaking change which adds functionality)
- [ ]  Refactoring (non-breaking change)
- [x]  Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the CONTRIBUTING document.
- [ ] I have added tests to cover my changes.

2023-11-17 23:09 UTC, heyitsmass reviewed
Can we decrease the spacing between the header and the title card slightly? It'll give displays with lower resolutions more screen to use - we're introducing a significant amount of dead space

2023-11-17 23:59 UTC, sonicspeed123 requested changes
I agree with @heyitsmass , decreasing the header and title card spacing will help with keeping things a little tighter for smaller screens like on mobile devices

2023-11-18 00:14 UTC, rdoinhs commented
> Can we decrease the spacing between the header and the title card slightly? It'll give displays with lower resolutions more screen to use - we're introducing a significant amount of dead space

> I agree with @heyitsmass , decreasing the header and title card spacing will help with keeping things a little tighter for smaller screens like on mobile devices

Of course, I reduced the height and added an optional param so we can tweak later to whatever value / values by query :)
<img width="2347" alt="Screenshot 2023-11-17 at 4 08 07 PM" src="https://github.com/heyitsmass/BayView/assets/38991991/38ce5c6f-aad3-4ac3-9db1-cc92a8b4c3fd">

2023-11-18 00:20 UTC, heyitsmass approved these changes

2023-11-18 00:22 UTC, sonicspeed123 approved these changes

2023-11-18 04:34 UTC, merged